[package]
name = "BlueStarOS"
version = "0.1.0"
edition = "2024"
[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"




[[bin]]
name = "blue_star_os"
path = "src/main.rs"
test = false
bench = false