[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.2.1"
buddy_system_allocator = "0.6"
spin = "0.9"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
